#!/bin/sh
BUILD_DIR=$3
umount $2 
dd if=${BUILD_DIR}/u-boot-aml.bin of=$1 
eject $1
echo please plugout and insert
read A
echo $A
umount $2 
mke2fs -L ROOTFS $2
mkdir -p  ${BUILD_DIR}/rootfs
mount -t ext2 $2 ${BUILD_DIR}/rootfs
cp $4/* ${BUILD_DIR}/rootfs -rf
cp $5  ${BUILD_DIR}/rootfs
umount $2
eject $1
echo FINISH